sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
env:
  matrix:
    - RAILS_VERSION='~> 4.2.0' SQLITE_VERSION='~> 1.3.6'
    - RAILS_VERSION='~> 5.0.0' SQLITE_VERSION='~> 1.3.6'
    - RAILS_VERSION='~> 5.1.0'
    - RAILS_VERSION='~> 5.2.x'
    - RAILS_VERSION='~> 6.0.0.beta3'

matrix:
  exclude:
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 6.0.0.beta3'
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 6.0.0.beta3'
    - rvm: 2.4.9
      env: RAILS_VERSION='~> 6.0.0.beta3'
